---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    pythonstack:
      demo:
        enabled: true
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: aio-apache
    run_list:
      - recipe[pythonstack::mysql_base]
      - recipe[pythonstack::postgresql_base]
      - recipe[pythonstack::mongodb_standalone]
      - recipe[pythonstack::memcache]
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::redis_single]
      - recipe[pythonstack::application_python]

  - name: aio-nginx
    run_list:
      - recipe[pythonstack::mysql_base]
      - recipe[pythonstack::postgresql_base]
      - recipe[pythonstack::mongodb_standalone]
      - recipe[pythonstack::memcache]
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::redis_single]
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        webserver: "nginx"

  - name: application_python_apache
    run_list:
      - recipe[pythonstack::application_python]

  - name: application_python_nginx
    run_list:
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        webserver: "nginx"

  - name: mysql
    run_list:
      - recipe[pythonstack::mysql_base]

  - name: postgresql
    run_list:
      - recipe[pythonstack::postgresql_base]
