---
driver:
  name: vagrant
provisioner:
  name: chef_zero
  attributes:
    pythonstack:
      demo:
        enabled: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'secret'
platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]
suites:
  - name: default
    run_list:
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::memcached]
      - recipe[pythonstack::mysql_master]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::application_python]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"
  - name: application_python_nginx
    run_list:
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::memcached]
      - recipe[pythonstack::mysql_master]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        webserver: "nginx"
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"
