---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    pythonstack:
      demo:
        enabled: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'secret'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]


suites:
  - name: mysql-master
    run_list:
      - recipe[pythonstack::mysql_master]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"
  - name: mysql-slave
    run_list:
      - recipe[pythonstack::mysql_slave]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"
  - name: application_python
    run_list:
      - recipe[pythonstack::application_python]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
  - name: varnish
    run_list:
      - recipe[pythonstack::varnish]
  - name: memcached
    run_list:
      - recipe[pythonstack::memcached]
  - name: all-in-one
    run_list:
      - recipe[pythonstack::mysql_master]
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::memcached]
      - recipe[pythonstack::application_python]
    attributes:
      mysql:
        server_root_password: "randompass"
        server_repl_password: "randompass"
        server_debian_password: "randompass"
      holland:
        password: "randompass"
